[test-removing-changes]

diff --git a/bigbluebutton-config/bin/bbb-conf b/bigbluebutton-config/bin/bbb-conf
--- a/bigbluebutton-config/bin/bbb-conf
+++ b/bigbluebutton-config/bin/bbb-conf
@@ -420,13 +420,13 @@ start_bigbluebutton () {
         TOMCAT_SERVICE=$TOMCAT_USER
     fi
 
-    systemctl start $TOMCAT_USER || {
-            echo
-            echo "# Warning: $TOMCAT_USER could not be started. Please, check BBB-LTI or BBB-Demo."
-            echo "#     Run the command:"
-            echo "#       sudo journalctl -u $TOMCAT_USER"
-            echo "#     To better understand the ERROR"
-        }
+    systemctl start $TOMCAT_SERVICE || {
+        echo
+        echo "# Warning: $TOMCAT_SERVICE could not be started. Please, check BBB-LTI or BBB-Demo."
+        echo "#     Run the command:"
+        echo "#       sudo journalctl -u $TOMCAT_SERVICE"
+        echo "#     To better understand the ERROR"
+    }
 
     systemctl start nginx freeswitch $REDIS_SERVICE bbb-apps-akka bbb-fsesl-akka bbb-rap-resque-worker bbb-rap-starter.service bbb-rap-caption-inbox.service $HTML5 $WEBHOOKS $ETHERPAD $PADS $BBB_WEB $BBB_LTI
 
@@ -1142,29 +1142,17 @@ check_state() {
 
     if bbb-conf --status | grep -q inactive; then
 
-        if systemctl list-units --full -all | grep -q $TOMCAT_USER.service; then
-            TOMCAT_SERVICE=$TOMCAT_USER
-
-            if bbb-conf --status | grep -q $TOMCAT_SERVICE; then
-                echo "# Warning: $TOMCAT_SERVICE is not started correctly"
-                echo "#"
-                echo "#   $(bbb-conf --status | grep inactive | grep $TOMCAT_SERVICE)"
-                echo "#"
-            fi
-            if bbb-conf --status | grep inactive | grep -vq $TOMCAT_SERVICE; then
-                echo "# Error: Detected some processes have not started correctly"
-                echo "#"
-                echo "#   $(bbb-conf --status | grep inactive | grep -v $TOMCAT_SERVICE)"
-                echo "#"
-            fi
-            
-        else
-            if bbb-conf --status | grep inactive; then
+        if bbb-conf --status | grep -q tomcat9; then
+            echo "# Warning: $TOMCAT_SERVICE is not started correctly"
+            echo "#"
+            echo "#   $(bbb-conf --status | grep inactive | grep $TOMCAT_SERVICE)"
+            echo "#"
+        fi
+        if bbb-conf --status | grep inactive | grep -vq tomcat9; then
             echo "# Error: Detected some processes have not started correctly"
             echo "#"
-            echo "#   $(bbb-conf --status | grep inactive)"
+            echo "#   $(bbb-conf --status | grep inactive | grep -v $TOMCAT_SERVICE)"
             echo "#"
-            fi
         fi
     fi
 
