--- new rerun

diff --git a/bigbluebutton-config/bin/bbb-conf b/bigbluebutton-config/bin/bbb-conf
--- a/bigbluebutton-config/bin/bbb-conf
+++ b/bigbluebutton-config/bin/bbb-conf
@@ -418,6 +418,14 @@ start_bigbluebutton () {
 
     if systemctl list-units --full -all | grep -q $TOMCAT_USER.service; then
         TOMCAT_SERVICE=$TOMCAT_USER
+        
+        systemctl start $TOMCAT_SERVICE || {
+            echo
+            echo "# Warning: $TOMCAT_SERVICE could not be started. Please, check BBB-LTI or BBB-Demo."
+            echo "#     Run the command:"
+            echo "#       sudo journalctl -u $TOMCAT_SERVICE"
+            echo "#     To better understand the ERROR"
+        }
     fi
 
     systemctl start $TOMCAT_SERVICE nginx freeswitch $REDIS_SERVICE bbb-apps-akka bbb-fsesl-akka bbb-rap-resque-worker bbb-rap-starter.service bbb-rap-caption-inbox.service $HTML5 $WEBHOOKS $ETHERPAD $PADS $BBB_WEB $BBB_LTI
@@ -1133,10 +1141,21 @@ check_state() {
     fi
 
     if bbb-conf --status | grep -q inactive; then
-        echo "# Error: Detected some processes have not started correctly"
-        echo "#"
-        echo "#   $(bbb-conf --status | grep inactive)"
-        echo "#"
+        if systemctl list-units --full -all | grep -q $TOMCAT_USER.service; then
+            TOMCAT_SERVICE=$TOMCAT_USER
+
+            if bbb-conf --status | grep -q inactive | grep -q $TOMCAT_SERVICE; then
+                echo "# Warning: $TOMCAT_SERVICE is not started correctly"
+                echo "#"
+            fi
+        fi
+
+        if bbb-conf --status | grep inactive; then
+            echo "# Error: Detected some processes have not started correctly"
+            echo "#"
+            echo "#   $(bbb-conf --status | grep inactive)"
+            echo "#"
+        fi
     fi
 
     if systemctl status freeswitch | grep -q SETSCHEDULER; then
